name: Dispatch deploy lambdas on merge to master
on:
  push:
    branches:
      - master
jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['elstr/repo-with-serverless-deploy', 'elstr/repo-with-serverless-deploy-2']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: changes-in-api
          client-payload: '{"env": "production"}'



